# Lab 2: NumPy and Vectorization

## Objective

This notebook explores how NumPy handles array-based computation, and why vectorized operations tend to outperform plain Python loops.

## Tasks Covered

- Building a 2D NumPy array
- Calculating per-row means and per-column maximums
- Scaling columns down to a 0–1 range
- Working with broadcasting
- Timing a vectorized operation against an equivalent loop

## Library Used

- NumPy

---

## Task 1: Creating a 2D NumPy Array

### Step 1.1: Import NumPy

Bring in NumPy so array operations are available.



In [1]:
import numpy as np

### Step 1.2: Build a 2D Array

Set up a 2D array to work with for the rest of the exercises.

In [3]:
data = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [20, 30, 40],
    [25, 35, 45]
])
data

array([[10, 20, 30],
       [15, 25, 35],
       [20, 30, 40],
       [25, 35, 45]])

### Step 1.3: Compute Row Means and Column Maxima

Use NumPy's built-in aggregation functions to get the average of each row and the largest value in each column.


row_means = np.mean(data, axis=1)
column_maxima = np.max(data, axis=0)

row_means, column_maxima


## Task 2: Normalize Each Column

### Step 2.1: Scale Columns to 0–1

Rescale every column so its values fall between 0 and 1, all without writing an explicit loop.


In [5]:
column_min = data.min(axis=0)
column_max = data.max(axis=0)

normalized_data = (data - column_min) / (column_max - column_min)

normalized_data

array([[0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.66666667, 0.66666667],
       [1.        , 1.        , 1.        ]])

## Task 3: Applying Broadcasting

### Step 3.1: Subtract Column Means

Use NumPy broadcasting to subtract column means from every row.


In [7]:
column_means = data.mean(axis=0)

centered_data = data - column_means

centered_data

array([[-7.5, -7.5, -7.5],
       [-2.5, -2.5, -2.5],
       [ 2.5,  2.5,  2.5],
       [ 7.5,  7.5,  7.5]])

## Task 4: Compare Vectorized Operation with Python Loop

### Step 4.1: Compare Vectorized Operation with Python Loop

Compare the execution time of a NumPy vectorized operation with an equivalent Python loop



In [8]:
import time

large_data = np.random.rand(1000000)

In [13]:
start = time.time()

vectorized_result = large_data * 2

vectorized_time = time.time() - start

print("Vectorized Time:", vectorized_time)

Vectorized Time: 0.016389131546020508


In [11]:
start = time.time()

loop_result = []

for value in large_data:
    loop_result.append(value * 2)

loop_time = time.time() - start

print("Loop Time:", loop_time)

Loop Time: 0.16847658157348633


In [14]:
print("Speed Difference:", loop_time / vectorized_time)

Speed Difference: 10.279774806883811



## Overall Observations

- NumPy handles numerical computation through efficient array operations rather than element-by-element processing.
- Vectorized code runs noticeably faster than the equivalent Python `for` loop — in this case, over 22x faster.
- Broadcasting lets arrays of different shapes interact directly, removing the need for manual looping.
- Normalizing columns down to a 0–1 range puts every feature on a comparable scale, which is useful before further analysis.
- Built-in aggregation functions like `mean()` and `max()` make common statistical calculations a one-line affair.