# Pandas and NumPy

Pandas and NumPy are two important Python libraries used for working with data.

NumPy is mainly focused on numerical computing and provides efficient array structures for calculations.

Pandas builds on these ideas by providing labeled data structures such as Series and DataFrames, which make it easier to work with tabular datasets.

This notebook covers the basic operations needed for numerical processing and data manipulation.

### Learning Objectives

- Understand NumPy arrays and their properties
- Perform numerical operations using NumPy
- Understand Pandas Series and DataFrames
- Load and inspect datasets using Pandas
- Select, filter, and modify data
- Perform basic data processing operations

In [1]:
import numpy as np
import pandas as pd

## What is NumPy?

NumPy stands for Numerical Python. It is designed to handle numerical data efficiently using multidimensional arrays.

A NumPy array stores values in a structured format and allows operations to be performed on many elements at the same time.

Some useful features of NumPy include:

- Fast numerical calculations
- One-dimensional and multidimensional arrays
- Mathematical and statistical functions
- Array indexing and slicing
- Reshaping and filtering

In [2]:
scores = np.array([12, 24, 36, 48, 60])

print("Array:", scores)
print("Type:", type(scores))
print("Shape:", scores.shape)
print("Dimensions:", scores.ndim)
print("Data type:", scores.dtype)

Array: [12 24 36 48 60]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Dimensions: 1
Data type: int64


### NumPy Array Operations

In [3]:
arr = np.array([10, 20, 30, 40, 50])

print("Addition:", arr + 5)
print("Subtraction:", arr - 5)
print("Multiplication:", arr * 2)
print("Division:", arr / 10)

Addition: [15 25 35 45 55]
Subtraction: [ 5 15 25 35 45]
Multiplication: [ 20  40  60  80 100]
Division: [1. 2. 3. 4. 5.]


### NumPy Indexing and Slicing

Indexing is used to access individual elements of an array, while slicing is used to access a range of elements.

In [5]:
print("First element:", arr[0])
print("Last element:", arr[-1])
print("First three elements:", arr[:3])
print("Elements from index 2:", arr[2:])

First element: 10
Last element: 50
First three elements: [10 20 30]
Elements from index 2: [30 40 50]


### NumPy 2D Arrays

A 2D NumPy array consists of rows and columns and can be used to represent tabular or matrix-like data.

The structure of a 2D array can be examined using properties such as shape, ndim, and size.

In [7]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(data)
print("Shape:", data.shape)
print("Dimensions:", data.ndim)
print("Size:", data.size)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape: (3, 3)
Dimensions: 2
Size: 9


### Indexing and Slicing in 2D Arrays

In a 2D array, an element can be accessed using its row and column index. Python uses zero-based indexing

In [8]:
print("First element:", data[0, 0])
print("Second row:", data[1])
print("Second column:", data[:, 1])
print("First two rows:")
print(data[:2])

First element: 10
Second row: [40 50 60]
Second column: [20 50 80]
First two rows:
[[10 20 30]
 [40 50 60]]


### Statistical Operations with NumPy

NumPy provides built-in functions for common statistical calculations such as mean, median, minimum, maximum, and standard deviation.

In [9]:
values = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(values))
print("Median:", np.median(values))
print("Minimum:", np.min(values))
print("Maximum:", np.max(values))
print("Standard deviation:", np.std(values))

Mean: 30.0
Median: 30.0
Minimum: 10
Maximum: 50
Standard deviation: 14.142135623730951


### Reshaping NumPy Arrays

Reshaping changes the structure of an array without changing its data.

The total number of elements must remain the same before and after reshaping

In [10]:
arr = np.arange(1, 13)

print("Original array:")
print(arr)

reshaped = arr.reshape(3, 4)

print("\nReshaped array:")
print(reshaped)

print("\nNew shape:", reshaped.shape)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

New shape: (3, 4)


### Conditional Filtering

NumPy allows us to filter array elements using conditions.

This is useful when we need to select observations that satisfy a specific condition.

In [12]:
values = np.array([10, 25, 40, 15, 60, 30])

filtered = values[values > 30]

print("Original values:", values)
print("Values greater than 30:", filtered)

Original values: [10 25 40 15 60 30]
Values greater than 30: [40 60]


### NumPy Summary

In this section, we learned:

- NumPy arrays and `ndarray`
- Array properties such as shape, dimensions, size, and data type
- Array indexing and slicing
- 2D arrays
- Mathematical and statistical operations
- Array reshaping
- Conditional filtering

These operations form the foundation for numerical data processing in Python.

## What is Pandas?

Pandas is a Python library used for data manipulation and analysis.

It provides two important data structures:

- **Series:** One-dimensional labeled data
- **DataFrame:** Two-dimensional tabular data

In [14]:
import pandas as pd

series = pd.Series([10, 20, 30, 40, 50])

print(series)
print("\nType:", type(series))

0    10
1    20
2    30
3    40
4    50
dtype: int64

Type: <class 'pandas.Series'>


### Pandas Series Indexing

A Series can be accessed using its index.

By default, Pandas assigns integer indexes starting from 0

In [15]:
print("First value:", series[0])
print("Second value:", series[1])
print("Last value:", series[4])

First value: 10
Second value: 20
Last value: 50


In [16]:
marks = pd.Series(
    [85, 90, 78, 92],
    index=["Maths", "Physics", "Chemistry", "English"]
)

print(marks)
print("\nPhysics marks:", marks["Physics"])

Maths        85
Physics      90
Chemistry    78
English      92
dtype: int64

Physics marks: 90


### What is a DataFrame?
A DataFrame is a two-dimensional labeled data structure in Pandas.

It is similar to a table with rows and columns.

DataFrames are commonly used for storing, manipulating, and analyzing datasets.

In [17]:
data = {
    "Name": ["Aman", "Riya", "Kartik", "Neha"],
    "Age": [21, 22, 20, 23],
    "Marks": [85, 92, 78, 88]
}

df_demo = pd.DataFrame(data)

print(df_demo)

     Name  Age  Marks
0    Aman   21     85
1    Riya   22     92
2  Kartik   20     78
3    Neha   23     88


## Inspecting a DataFrame

Pandas provides useful functions to quickly understand a dataset.

- `head()` shows the first rows.
- `tail()` shows the last rows.
- `info()` shows column names, data types, and non-null values.
- `describe()` gives a statistical summary of numerical columns.

In [20]:
df = pd.read_csv("../../data/WineQT (3).csv")
print(df.head())

   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  Id  
0      9.4        5   0  
1      9.8        5   1  
2      9

In [21]:
print(df.tail())

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1138            6.3             0.510         0.13             2.3      0.076   
1139            6.8             0.620         0.08             1.9      0.068   
1140            6.2             0.600         0.08             2.0      0.090   
1141            5.9             0.550         0.10             2.2      0.062   
1142            5.9             0.645         0.12             2.0      0.075   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1138                 29.0                  40.0  0.99574  3.42       0.75   
1139                 28.0                  38.0  0.99651  3.42       0.82   
1140                 32.0                  44.0  0.99490  3.45       0.58   
1141                 39.0                  51.0  0.99512  3.52       0.76   
1142                 32.0                  44.0  0.99547  3.57       0.71   

      alcohol  quality    Id  
1138     11.0      

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64  
 12  Id                    1143 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 116.2 KB


In [23]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
count,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000,1143.000000
mean,8.311111,0.531339,0.268364,2.532152,0.086933,15.615486,45.914698,0.996730,3.311015,0.657708,10.442111,5.657043,804.969379
std,1.747595,0.179633,0.196686,1.355917,0.047267,10.250486,32.782130,0.001925,0.156664,0.170399,1.082196,0.805824,463.997116
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000,0.000000
25%,7.100000,0.392500,0.090000,1.900000,0.070000,7.000000,21.000000,0.995570,3.205000,0.550000,9.500000,5.000000,411.000000
50%,7.900000,0.520000,0.250000,2.200000,0.079000,13.000000,37.000000,0.996680,3.310000,0.620000,10.200000,6.000000,794.000000
75%,9.100000,0.640000,0.420000,2.600000,0.090000,21.000000,61.000000,0.997845,3.400000,0.730000,11.100000,6.000000,1209.500000
max,15.900000,1.580000,1.000000,15.500000,0.611000,68.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000,1597.000000


### Selecting Columns
Pandas allows us to select one or more columns from a DataFrame.

Selecting specific columns is useful when we want to focus on particular features during data analysis.

In [25]:
# Select one column
print(df["alcohol"])

0        9.4
1        9.8
2        9.8
3        9.8
4        9.4
        ... 
1138    11.0
1139     9.5
1140    10.5
1141    11.2
1142    10.2
Name: alcohol, Length: 1143, dtype: float64


In [26]:
# Select multiple columns
selected = df[["alcohol", "pH", "quality"]]

print(selected.head())

   alcohol    pH  quality
0      9.4  3.51        5
1      9.8  3.20        5
2      9.8  3.26        5
3      9.8  3.16        6
4      9.4  3.51        5


### Selecting Rows
Rows can be selected using conditions.

This is useful for filtering observations based on specific requirements.

In [29]:
# Wines with quality greater than 6
high_quality = df[df["quality"] > 6]

print(high_quality.head())

    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
7             7.3              0.65         0.00             1.2      0.065   
8             7.8              0.58         0.02             2.0      0.073   
12            8.5              0.28         0.56             1.8      0.092   
27            8.1              0.38         0.28             2.1      0.066   
89            8.0              0.59         0.16             1.8      0.065   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
7                  15.0                  21.0   0.9946  3.39       0.47   
8                   9.0                  18.0   0.9968  3.36       0.57   
12                 35.0                 103.0   0.9969  3.30       0.75   
27                 13.0                  30.0   0.9968  3.23       0.73   
89                  3.0                  16.0   0.9962  3.42       0.92   

    alcohol  quality   Id  
7      10.0        7    7  
8       9.5       

### Selecting Rows and Columns with loc and iloc
loc is used for label-based selection.

iloc is used for position-based selection using integer indexes.

In [30]:
print(df.loc[0, "alcohol"])
print(df.loc[0:4, ["alcohol", "pH", "quality"]])

9.4
   alcohol    pH  quality
0      9.4  3.51        5
1      9.8  3.20        5
2      9.8  3.26        5
3      9.8  3.16        6
4      9.4  3.51        5


In [31]:
# Using iloc
print(df.iloc[0, 10])
print(df.iloc[0:5, 10:13])

9.4
   alcohol  quality  Id
0      9.4        5   0
1      9.8        5   1
2      9.8        5   2
3      9.8        6   3
4      9.4        5   4


### Filtering with Multiple Conditions

Pandas allows us to filter rows using multiple conditions.

- `&` means **AND**
- `|` means **OR**
- Each condition should be written inside parentheses.

In [33]:
# AND condition
filtered = df[(df["quality"] >= 6) & (df["alcohol"] > 10)]

print(filtered.head())

    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
12            8.5             0.280         0.56             1.8      0.092   
26            7.8             0.600         0.14             2.4      0.086   
30            7.5             0.490         0.20             2.6      0.332   
38            7.6             0.510         0.15             2.8      0.110   
48            8.0             0.705         0.05             1.9      0.074   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
12                 35.0                 103.0   0.9969  3.30       0.75   
26                  3.0                  15.0   0.9975  3.42       0.60   
30                  8.0                  14.0   0.9968  3.21       0.90   
38                 33.0                  73.0   0.9955  3.17       0.63   
48                  8.0                  19.0   0.9962  3.34       0.95   

    alcohol  quality  Id  
12     10.5        7  16  
26     10.8        6

In [34]:
# OR condition
filtered = df[(df["quality"] >= 7) | (df["alcohol"] > 13)]

print(filtered.head())

    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
7             7.3              0.65         0.00             1.2      0.065   
8             7.8              0.58         0.02             2.0      0.073   
12            8.5              0.28         0.56             1.8      0.092   
27            8.1              0.38         0.28             2.1      0.066   
32            4.6              0.52         0.15             2.1      0.054   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
7                  15.0                  21.0   0.9946  3.39       0.47   
8                   9.0                  18.0   0.9968  3.36       0.57   
12                 35.0                 103.0   0.9969  3.30       0.75   
27                 13.0                  30.0   0.9968  3.23       0.73   
32                  8.0                  65.0   0.9934  3.90       0.56   

    alcohol  quality  Id  
7      10.0        7   7  
8       9.5        7

In [35]:
# Multiple columns with conditions
filtered = df[
    (df["quality"] >= 6) &
    (df["pH"] < 3.5) &
    (df["alcohol"] > 10)
]

print(filtered.head())

    fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
12            8.5             0.280         0.56             1.8      0.092   
26            7.8             0.600         0.14             2.4      0.086   
30            7.5             0.490         0.20             2.6      0.332   
38            7.6             0.510         0.15             2.8      0.110   
48            8.0             0.705         0.05             1.9      0.074   

    free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
12                 35.0                 103.0   0.9969  3.30       0.75   
26                  3.0                  15.0   0.9975  3.42       0.60   
30                  8.0                  14.0   0.9968  3.21       0.90   
38                 33.0                  73.0   0.9955  3.17       0.63   
48                  8.0                  19.0   0.9962  3.34       0.95   

    alcohol  quality  Id  
12     10.5        7  16  
26     10.8        6

Sorting DataFrame
Pandas allows us to sort rows based on one or more columns.

sort_values() is used to arrange data in ascending or descending order.

In [37]:
# Sort by alcohol in ascending order
sorted_df = df.sort_values("alcohol")

print(sorted_df[["alcohol", "quality"]].head())

      alcohol  quality
388       8.4        6
368       8.4        3
1023      8.5        5
263       8.7        6
1051      8.8        5


In [38]:
# Sort by alcohol in descending order
sorted_df = df.sort_values("alcohol", ascending=False)

print(sorted_df[["alcohol", "quality"]].head())

     alcohol  quality
462     14.9        5
419     14.0        8
589     14.0        7
898     14.0        6
98      14.0        6


### Creating a New Column
A new column can be created by assigning a value or calculation to a new column name.

In [39]:
df["alcohol_percentage"] = df["alcohol"]

print(df[["alcohol", "alcohol_percentage"]].head())

   alcohol  alcohol_percentage
0      9.4                 9.4
1      9.8                 9.8
2      9.8                 9.8
3      9.8                 9.8
4      9.4                 9.4
